# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Karnet BDD
                                 A QGIS plugin
 Ce plugin sert à valider les données brutes issue des données brutes Karum
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-24
        copyright            : (C) 2024 by Jules-Yann Milleret - Éconumérik/Karum
        email                : jy.millleret@econumerik.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Karnet class from file Karnet.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Karnet import Karnet
    return Karnet(iface)
